name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Maximize Runner Space
        # هذا الأمر يمسح حرفياً جيجابايتات من الملفات غير الضرورية في سيرفر GitHub
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/include/google
          sudo rm -rf /usr/local/lib/node_modules
          docker image prune -a -f

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev build-essential
          pip install --user --upgrade buildozer Cython==0.29.33 kivy

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # تنظيف أي بقايا سابقة قبل البدء
          buildozer android clean
          yes | buildozer -v android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MobileApp-Final
          path: bin/*.apk
